### ISSUE TITLE
Docs for environment file mgm and running proxy locally

### ISSUE THREAD

**Issue by mskyttner** [chrisIsen/specify-docker#2]
Frågor till nästa session
* root-lösenord till MySQL?
* Hur hänger proxyn ihop med letsencrypt och webbservern? Jag behöver en praktisk förklaring i stora block :-)
* Dölja känslig info på github, t ex .env-filen?

**Comment by chrisIsen** [comment]
Löste detta. Nu är utvecklingsmiljön igång.
* Ändrade recraft.me till gnmspecify.se där jag hittade det med grep.
* Kopierade /var/lib/docker/volumes/specify-docker_data_certs/_data från prod till dev.
* importerade backup av prod-db.

**Comment by mskyttner** [comment]
:+1:
