### ISSUE TITLE
Fix connection to specify6.gnmspecify.se.

### ISSUE THREAD

**Issue by chrisIsen** [chrisIsen/specify-docker#7]

**Comment by chrisIsen** [comment]
Webbläsaren svarar som den ska med en prompt att ansluta till NoVnc. När jag klickar anslut kommer varning att anslutningen misslyckas.

Loggen på ui ger följande (loopas kontinuerligt)
```
2021-04-26 13:40:23,140 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 13:40:23,142 INFO exited: novnc (exit status 1; not expected)
```

Log från wssix:
`2021/04/26 13:32:39 [error] 34#34: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.3, server: , request: "GET /websockify HTTP/1.1", upstream: "http://172.23.0.6:8083/websockify", host: "specify6.gnmspecify.se"`

**Comment by mskyttner** [comment]
Jag såg också detta, men verkar vara fixat i #9, ser du samma?

**Comment by mskyttner** [comment]
Jag tror det fungerar bättre i #9: 
![image](https://user-images.githubusercontent.com/1715840/122049486-c2d56500-cde2-11eb-9cb1-e01dc4bd7a1d.png)

Men ser ut som att då behöver någon config ändras lite (metadatan pekar inte till sig själv i .xml-filen)?
